### ISSUE TITLE
About text features of BLIP2

### ISSUE THREAD

**Issue by winnerwu6** [Caoyichao/UniHOI#1]
Do you use the features output by Qformer as a classifier or the features output by opt 2.7B as a classifier?

**Comment by winnerwu6** [comment]
Can you explain how to use language models to get Textual Features from text descriptions? I would be extremely grateful if you could explain it in detail！！

**Comment by Caoyichao** [comment]
> Do you use the features output by Qformer as a classifier or the features output by opt 2.7B as a classifier?

We adopt the blip2-opt-2.7b to extract image features as :
`model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-opt-2.7b", torch_dtype=torch.float16) 
model.to(device)
print('model loading over!')

for img_path in tqdm.tqdm(images):
  img = Image.open(img_path).convert('RGB')   
  inputs = processor(img, return_tensors="pt").to(device, torch.float16)
  query_out = model.generate(**inputs, max_new_tokens=20)
`

**Comment by Caoyichao** [comment]
> Can you explain how to use language models to get Textual Features from text descriptions? I would be extremely grateful if you could explain it in detail！！

For the text feature, we adopt the lavis package to generate [CLS] token:

from lavis.models import load_model_and_preprocess
blip_model, vis_processors, txt_processors = load_model_and_preprocess(name='blip2_feature_extractor', model_type='pretrain_vitL', is_eval=True, device=device)

text_embedding = blip_model.extract_features({"text_input": text_inputs}, mode="text").text_embeds_proj[:,0,:]
text_embedding_del = blip_model.extract_features({"text_input": text_inputs_del}, mode="text").text_embeds_proj[:,0,:]
obj_text_embedding = blip_model.extract_features({"text_input": obj_text_inputs}, mode="text").text_embeds_proj[:,0,:]

**Comment by winnerwu6** [comment]
Thank you very much for your patient response, and thank you for your remarkable work.

**Comment by Vincent-luo** [comment]
> > Do you use the features output by Qformer as a classifier or the features output by opt 2.7B as a classifier?
> 
> We adopt the blip2-opt-2.7b to extract image features as : `model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-opt-2.7b", torch_dtype=torch.float16) model.to(device) print('model loading over!')
> 
> for img_path in tqdm.tqdm(images): img = Image.open(img_path).convert('RGB') inputs = processor(img, return_tensors="pt").to(device, torch.float16) query_out = model.generate(**inputs, max_new_tokens=20) `

Seems like to me, `query_out` is more like textual feature in some way because it will be decoded into a caption when using `Blip2ForConditionalGeneration` model. I am curious why not directly use the query features outputed by Q-former as image features.
