### ISSUE TITLE
Zero-Shot HOI Detection Setting

### ISSUE THREAD

**Issue by hutuo1213** [Caoyichao/UniHOI#2]
Hi,
We have recently considered using a two-stage method for Zero-Shot HOI Detection, but we have some confusion about the detailed setup.
You use the following formula for Zero-Shot HOI Detection:
![image](https://github.com/Caoyichao/UniHOI/assets/112799241/d3286bb2-40f8-4209-96ee-66825952aa8c)
My understanding is that the text features (600) do similarity calculations with the final interaction representation to get the interaction categories.

1. unseen combination (UC) has seen all verbs and objects. The two-stage method seems to handle this case directly. Alternatively, the "similarity computation" is still used.

2. Unseen Objects (UO) Have not seen a few objects.
We found that in GEN-VLKT (hico_text_label.py), there are only interaction categories related to unseen objects. So, are unseen objects used as GTs in training for the object detection task? Does this part still use "similarity computation"?

3. Unseen actions (UV) have not seen few verbs. Does this part still use "similarity computation"?

**Comment by Caoyichao** [comment]
Thank you for your attention. You can refer to the GEN-VLKT for this setting. To ensure the alignment between two modalities, we directly replace the CLIP text encoder in GEN-VLKT to BLIP2-OPT. Other setting are remain unchanged.
